[build]
  functions = "netlify/functions"
  publish = "frontend"

[functions]
  node_bundler = "esbuild"

[functions."driver"]
  schedule = "*/1 * * * *"

[functions."telegram-supervisor"]
  schedule = "*/15 * * * *"
